COPY $SDK_DIR /opt/sdk-csharp
WORKDIR /opt/sdk-csharp

RUN chmod 755 build.sh

# OpenAPI Builder for csharp is broken
# RUN ./build.sh
# WORKDIR /opt/executor
# RUN mv ../sdk-csharp/bin . && rm -rf ../sdk-csharp
